### ISSUE TITLE
[Wishlist] port µGFX 

### ISSUE THREAD

**Issue by danielinux** [insane-adding-machines/frosted#107]
"µGFX is a library to interface different displays and touchscreens to your embedded application"

http://ugfx.io
~~https://github.com/Tecnologic/uGFX~~
https://git.ugfx.io/uGFX/uGFX

**Comment by danielinux** [comment]
Hello @k0d - could you update us on the status of the port? Do you need extra helping hands?

**Comment by sferrini** [comment]
Hey @danielinux, how will the µGFX library be linked to the kernel? It will be just an executable? Because I read the [license](http://ugfx.io/license.html) and for commercial use it's a [paid](http://ugfx.io/pricing) one.

**Comment by sferrini** [comment]
Also I guess the upstream repo is this one: https://git.ugfx.io/uGFX/uGFX

**Comment by danielinux** [comment]
@sferrini no link to the kernel... this is a userspace project, so no worries about license issues.
Please note the orange tag on this issue that says "Applications and libraries".

**Comment by sferrini** [comment]
Oh right @danielinux! I didn't see it, thanks 👍

**Comment by k0d** [comment]
No update as I've returned back to work after sickleave and there is 20x the normal workload right now. So Frosted dev is on hold for a short time for me.

**Comment by danielinux** [comment]
@k0d ugh... sorry to hear. Hope you are feeling better now.

**Comment by danielinux** [comment]
Currently being handled by the uGFX team, so closing this for now.
