### ISSUE TITLE
MAC address value variation

### ISSUE THREAD

**Issue by kuldeepdhaka** [insane-adding-machines/frosted#110]
https://github.com/insane-adding-machines/frosted/blob/master/kernel/drivers/devusb_cdc_ecm.c#L168

`static const char usb_macaddr[] = "005af341b4c9";`
`static const uint8_t mac_addr[6] = { 0, 0x5a, 0xf3, 0x41, 0xb4, 0xca };`

Is the difference intentional?  (last byte `ca`)

**Comment by danielinux** [comment]
yes, those are the two endpoints, "c9" is being assigned on the host side, while "ca" is on the device side.
