### ISSUE TITLE
How using port uGFX

### ISSUE THREAD

**Issue by nathanLoretan** [insane-adding-machines/frosted#118]
Hello, I've heard that it is possible to use the graphic functions from ugfx library with the OS frosted. I want to know how can I link both?

**Comment by danielinux** [comment]
This is currently a joint work in progress between insane-adding-machines and the ugfx.io community.
There is no port available yet, but we'll keep you informed when we have a working uGFX port compiling & working on frosted.

**Comment by nathanLoretan** [comment]
I know. The port to bind uGFX and frosted is almost finished. I must implement the semaphore. But Joel Bodenmann told me that frosted has already implemented the framebuffer support to use graphic functions.

**Comment by danielinux** [comment]
- compile frosted with framebuffer support
- open "/dev/fb0"
- set your RGB palette via     ioctl(fd_fb, IOCTL_FB_PUTCMAP,  ...);
- use write/lseek to fill the framebuffer
