### ISSUE TITLE
Provide a better POSIX compatibility for semaphores

### ISSUE THREAD

**Issue by danielinux** [insane-adding-machines/frosted#119]
- [x] rework `sem_init` so it accepts three parameters and sets the return value into the `sem` argument
- [x] Implement `sem_timedwait`
- [x] Implement `sem_trywait`

**Comment by brabo** [comment]
WIP - in testing/debugging phase atm..

**Comment by danielinux** [comment]
- [x] rework `sem_init` ...: fixed by @brabo in 49ebb14c807103080ac62a19dc7087e1fbcec1de

_verified_

**Comment by danielinux** [comment]
Acceptance tests here:
insane-adding-machines/frosted-userland@7154946b53b6f030479556e1a57a1682a96b7edf

**Comment by danielinux** [comment]
trywait: _verified_ OK

**Comment by danielinux** [comment]
timedwait: _verified_ OK. 

Closing...
