### ISSUE TITLE
Proper system clocks

### ISSUE THREAD

**Issue by brabo** [insane-adding-machines/frosted#120]
- [x]  use jiffies and read that as CLOCK_MONOTONIC
- [x] use rt offset and read/write that as CLOCK_REALTIME and for [s|g]ettimeofday()

**Comment by danielinux** [comment]
Where was CLOCK_MONOTONIC supposed to be defined in kernel space? I had to add an explicit define in `sys.c` because I cannot find any reference to that symbol in kernel code. Missing common header?

**Comment by brabo** [comment]
<time.h> as:
https://github.com/insane-adding-machines/frosted/blob/master/kernel/sys.c#L23

**Comment by danielinux** [comment]
Time.h is nowhere to be found in kernel code. Is it a libc include? Libc include are ignored in kernel, as we compile with nostdinc.

**Comment by brabo** [comment]
it is in newlib. that flag seems gone, compiles and works fine this way. i agree we should split it off to frosted-headers though and include that both ways.

**Comment by danielinux** [comment]
The stdinc problem is not only related to this. This issue can be closed, but the problem persists until we fix #121 

Thanks
