### ISSUE TITLE
Add support for route.h in libC

### ISSUE THREAD

**Issue by danielinux** [insane-adding-machines/frosted#22]
- [x] Add support for route.h in toolchain
- [ ] write userland netutils/route to add/rm/list routes

**Comment by danielinux** [comment]
Support for net/route.h in newlib added:
https://github.com/insane-adding-machines/newlib/commit/18862e0fd1b8531f269f72b700195a6d65bdb99c

**Comment by danielinux** [comment]
route binary: work in progress
https://github.com/insane-adding-machines/frosted-userland/blob/master/netutils/route.c

currently missing parameters parsing from command line.

**Comment by danielinux** [comment]
@NicoLiberato - were you going to work on this?

**Comment by ncandio** [comment]
As soon I have a fast Internet connection. I will provide you asap.

**Comment by danielinux** [comment]
@NicoLiberato ping?

**Comment by ncandio** [comment]
Hi Danielinux, I have high bandwidth, let's back on track
Il 10/giu/2016 10:33, "Daniele Lacamera" notifications@github.com ha
scritto:

**Comment by danielinux** [comment]
Continuing on #62
