### ISSUE TITLE
[Wishlist] Compile kilo editor in userland

### ISSUE THREAD

**Issue by danielinux** [insane-adding-machines/frosted#57]
Latest arm-frosted-eabi-gcc cannot compile kilo (https://github.com/antirez/kilo).

Missing library calls: 
- [x] getline() (perhaps use the implementation in fresh?)
- [x] ftruncate() (trivial, implement as proxy syscall in libC)

**Comment by maximevince** [comment]
:+1:

**Comment by danielinux** [comment]
ftruncate added in 498e3422f7f6d184f4f390576717bcf6e224c594

**Comment by danielinux** [comment]
getline added in newlib.

kilo compiling but not working properly over serial line. Needs investigation.

**Comment by danielinux** [comment]
kilo works decently now!
