### ISSUE TITLE
Missing syscalls/library calls

### ISSUE THREAD

**Issue by danielinux** [insane-adding-machines/frosted#6]
- [x] vfork
- [x] sigaction
- [x] sigisemptyset
- [x] sigprocmask
- [x] sigsuspend
- [x] fnmatch
- [x] tcgetattr
- [x] getrlimit
- [x] setrlimit
- [x] umask
- [x] pipe
- [x] _malloc_trim_r

**Comment by maximevince** [comment]
fnmatch will indeed be provided by newlib

**Comment by danielinux** [comment]
Implementation done. Test in progress...
