### ISSUE TITLE
hardcoded incorrect value of stm32_usb buffer in usbd_init

### ISSUE THREAD

**Issue by kuldeepdhaka** [insane-adding-machines/frosted#63]
in usbd_init the buffer length is incorrectly hardcoded to 128.  
https://github.com/insane-adding-machines/frosted/blob/master/kernel/drivers/stm32_usb.c#L55 
https://github.com/insane-adding-machines/frosted/blob/master/kernel/drivers/usb.h#L28 
https://github.com/insane-adding-machines/frosted/blob/master/kernel/drivers/usb.h#L19

**Comment by danielinux** [comment]
What should be the appropriate value?

**Comment by kuldeepdhaka** [comment]
fixed in 2915780aad3541a59e4a54eb5edcea871fdc9551
