### ISSUE TITLE
FatFS: add write support

### ISSUE THREAD

**Issue by danielinux** [insane-adding-machines/frosted#71]
should be possible to write on a mounted Fat16/32 partition.

**Comment by brabo** [comment]
fatfs_write sortof working now, write causes trailing bytes to be lost.

**Comment by brabo** [comment]
- [x] update file sizes in vfs/fat
- [ ] add fatfs_truncate

**Comment by brabo** [comment]
New driver can write. Truncate still listed in #124.
Closing this one, main objective has been reached!
