### ISSUE TITLE
LTDC: buffer allocation & blank

### ISSUE THREAD

**Issue by sferrini** [insane-adding-machines/frosted#81]
Reading the `stm32f7_ltdc` driver implementation I was trying to understand the `screen_buffer` and how this driver in general works.

And I've noticed at this [line](https://github.com/insane-adding-machines/frosted/blob/master/kernel/drivers/stm32f7_ltdc.c#L59) that the buffer allocation is done calculating the size like so: `fb->var.xres * fb->var.xres * (fb->var.bits_per_pixel/8)`. Shouldn't be calculated also involving the `yres`? So like `fb->var.xres * fb->var.yres * (fb->var.bits_per_pixel/8)`?

Also in the function `ltdc_blank` at this [line](https://github.com/insane-adding-machines/frosted/blob/master/kernel/drivers/stm32f7_ltdc.c#L169) shouldn't `fb->var.bits_per_pixel` be `(fb->var.bits_per_pixel/8)`?

Maybe I get the implementation in a wrong way, so sorry in advance if so.

@maximevince can you please have a look?

Let me know what you think, and I'll do a PR if needed.

Thanks

**Comment by danielinux** [comment]
@sferrini thanks for reporting. Indeed let's wait for @maximevince comment.

**Comment by maximevince** [comment]
@sferrini hey, thanks for reviewing our code, we like that.
that is a huge typo indeed, nicely spotted!
if you make another pull request, we'll integrate that.

**Comment by maximevince** [comment]
Both of your suggestions are correct, by the way!

The LTDC implementation right now is _very_ basic; i just rushed into it, to get DOOM working :)
So any improvements are welcome!

**Comment by sferrini** [comment]
@maximevince It's a pleasure! I'll do the PR in a bit 😉

**Comment by brabo** [comment]
:D
