### ISSUE TITLE
Finalize pthread implementation

### ISSUE THREAD

**Issue by danielinux** [insane-adding-machines/frosted#94]
https://linux.die.net/man/7/pthreads

**Comment by danielinux** [comment]
TODO:
- [x] implement pthread_join properly
- [ ] multiplex signals properly

**Comment by danielinux** [comment]
@ichigo663 - since you are busy with the scheduler, is it perhaps interesting for you to continue on this one?
We need proper join/detach implementation. One thread in each group can call join, maybe you can reuse the ZOMBIE state if the thread is joinable.

**Comment by acardace** [comment]
Ok! I'll start looking into it!

**Comment by danielinux** [comment]
Looks like only pthread_kill is urgently missing (along with proper signal distribution).

**Comment by danielinux** [comment]
This can be closed for now, as micropython successfully compiled with thread support. 

More pthread-related feature requests belong to new issues.
